"""add count column to order product association table

Revision ID: 249b25960f5b
Revises: 53c6fdec5f03
Create Date: 2025-06-22 10:44:06.293090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "249b25960f5b"
down_revision: Union[str, Sequence[str], None] = "53c6fdec5f03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association_table",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_association_table", "count")
    # ### end Alembic commands ###
